services:
  apolo-music-bot:
    build: .
    image: apolo-music-bot:latest
    container_name: apolo-music-bot
    restart: unless-stopped
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
