pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        mavenCentral()
        maven { url = 'https://jitpack.io' }
        maven { url = 'https://maven.lavalink.dev/releases' }
    }
}

rootProject.name = 'apolo-music-bot'
