spring.application.name=apolo-music-bot
spring.profiles.active=dev

discord.bot.token=${DISCORD_BOT_TOKEN}

logging.level.net.dv8tion.jda=DEBUG
logging.level.net.dv8tion.jda.api.audio=DEBUG
logging.level.net.dv8tion.jda.api.requests=DEBUG
